SOURCE_PATHS += $(BASE_PATH)/src/libmetal
SOURCE_PATHS += $(BASE_PATH)/src/remoteproc
SOURCE_PATHS += $(BASE_PATH)/src/rpmsg
SOURCE_PATHS += $(BASE_PATH)/src/virtio
SOURCE_PATHS += $(BASE_PATH)/src/virtual_driver
SOURCE_PATHS += $(BASE_PATH)/src/openamp
CFLAGS += -O3 -DMETAL_FREERTOS -DMETAL_INTERNAL -DMETAL_MAX_DEVICE_REGIONS=2 -DVIRTIO_SLAVE_ONLY -D__LOG_TRACE_IO_ -DNO_ATOMIC_64_SUPPORT -DUSE_HAL_DRIVER